version: '3.8'

services:
  starrocks:
    image: starrocks/allin1-ubuntu
    container_name: starrocks_radiant
    ports:
      - "9030:9030"
      - "8030:8030"
      - "8040:8040"
    healthcheck:
      test: >
        curl -sf http://localhost:8030/api/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: radiant
      POSTGRES_USER: radiant
      POSTGRES_DB: radiant

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
        KC_HOSTNAME: localhost
        KC_HOSTNAME_PORT: 8080
        KC_HOSTNAME_STRICT: false
        KC_HOSTNAME_STRICT_HTTPS: false
        KC_LOG_LEVEL: info
        KC_METRICS_ENABLED: true
        KC_HEALTH_ENABLED: true
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "8080:8080"

  init:
    image: starrocks/allin1-ubuntu
    depends_on:
       starrocks:
         condition: service_healthy
    volumes:
      - ./scripts/init-sql:/docker-entrypoint-initdb.d
    entrypoint: >
      /bin/bash -c "
      mysql -hstarrocks -P9030 -uroot < /docker-entrypoint-initdb.d/init_starrocks.sql;"