name: Publish Image Using Semver Tag

on:
  push:
    tags:
      - v*

jobs:
  push:
    if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    name: Publish Image using tags
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Push the image on the registry
        uses: Ferlab-Ste-Justine/action-push-image@v2
        with:
          username: ${{ secrets.FERLAB_DOCKER_HUB_USER }}
          password: ${{ secrets.FERLAB_DOCKER_HUB_TOKEN }}
          image: ferlabcrsj/radiant-api
          tag_format: "{semver}"
          location: ./backend
          dockerfile: ./backend/Dockerfile

      - name: Push frontend image on the registry
        uses: Ferlab-Ste-Justine/action-push-image@v2
        with:
          username: ${{ secrets.FERLAB_DOCKER_HUB_USER }}
          password: ${{ secrets.FERLAB_DOCKER_HUB_TOKEN }}
          image: ferlabcrsj/radiant-portal
          tag_format: "{semver}"
          location: ./frontend
          dockerfile: ./frontend/Dockerfile.radiant